[build]
base = "/"
command = "pnpm install && pnpm build"
publish = "kiosk/dist"
functions = "kiosk-functions"

[build.environment]
NODE_VERSION = "22"

[context.production]
command = "pnpm install && pnpm build"

[context.deploy-preview]
command = "pnpm install && pnpm build"

[context.branch-deploy]
command = "pnpm install && pnpm build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
